### ISSUE TITLE
 'wtServer' object has no attribute 'listen_url'

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc-PG3/udi-wirelesstag-poly#41]
```
2021-10-03 02:59:56,144 Controller polyinterface      INFO     polyinterface:reportDriver: Updating Driver 3bdf6bace4a218 - GV14: 80655, uom: 25
2021-10-03 02:59:56,151 Thread-1345 polyinterface      ERROR    polyinterface:write: self._target(*self._args, **self._kwargs)
2021-10-03 02:59:56,153 Thread-1345 polyinterface      ERROR    polyinterface:write: File "/var/polyglot/nodeservers/WirelessTag/wt_nodes/wTagManager.py", line 314, in _set_url_config_false
2021-10-03 02:59:56,157 Thread-1345 polyinterface      ERROR    polyinterface:write: self._set_url_config(force=False)
2021-10-03 02:59:56,158 Thread-1345 polyinterface      ERROR    polyinterface:write: File "/var/polyglot/nodeservers/WirelessTag/wt_nodes/wTagManager.py", line 328, in _set_url_config
2021-10-03 02:59:56,160 Thread-1345 polyinterface      ERROR    polyinterface:write: tag.set_url_config(force=force)
2021-10-03 02:59:56,161 Thread-1345 polyinterface      ERROR    polyinterface:write: File "/var/polyglot/nodeservers/WirelessTag/wt_nodes/wTag.py", line 237, in set_url_config
2021-10-03 02:59:56,163 Thread-1345 polyinterface      ERROR    polyinterface:write: url = self.controller.wtServer.listen_url
2021-10-03 02:59:56,164 Thread-1345 polyinterface      ERROR    polyinterface:write: AttributeError
2021-10-03 02:59:56,164 Thread-1345 polyinterface      ERROR    polyinterface:write: :
2021-10-03 02:59:56,165 Thread-1345 polyinterface      ERROR    polyinterface:write: 'wtServer' object has no attribute 'listen_url'
2021-10-03 03:00:54,496 Controller polyinterface      ERROR    polyinterface:write: Exception in thread
2021-10-03 03:00:54,497 Controller polyinterface      ERROR    polyinterface:write: Controller
2021-10-03 03:00:54,497 Controller polyinterface      ERROR    polyinterface:write: :
2021-10-03 03:00:54,498 Controller polyinterface      ERROR    polyinterface:write: Traceback (most recent call last):
2021-10-03 03:00:54,498 Controller polyinterface      ERROR    polyinterface:write: File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-10-03 03:00:54,502 Controller polyinterface      ERROR    polyinterface:write: self.run()
2021-10-03 03:00:54,502 Controller polyinterface      ERROR    polyinterface:write: File "/usr/local/lib/python3.8/threading.py", line 870, in run
2021-10-03 03:00:54,505 Controller polyinterface      ERROR    polyinterface:write: self._target(*self._args, **self._kwargs)
2021-10-03 03:00:54,506 Controller polyinterface      ERROR    polyinterface:write: File "/var/polyglot/.local/lib/python3.8/site-packages/polyinterface/polyinterface.py", line 857, in _parseInput
2021-10-03 03:00:54,510 Controller polyinterface      ERROR    polyinterface:write: self.nodes[input[key]['address']].query()
2021-10-03 03:00:54,510 Controller polyinterface      ERROR    polyinterface:write: File "/var/polyglot/nodeservers/WirelessTag/wt_nodes/wtController.py", line 181, in query
2021-10-03 03:00:54,512 Controller polyinterface      ERROR    polyinterface:write: self.is_signed_in()
2021-10-03 03:00:54,512 Controller polyinterface      ERROR    polyinterface:write: File "/var/polyglot/nodeservers/WirelessTag/wt_nodes/wtController.py", line 290, in is_signed_in
2021-10-03 03:00:54,514 Controller polyinterface      ERROR    polyinterface:write: mgd = self.wtServer.IsSignedIn()
2021-10-03 03:00:54,515 Controller polyinterface      ERROR    polyinterface:write: File "/var/polyglot/nodeservers/WirelessTag/wtServer.py", line 239, in IsSignedIn
2021-10-03 03:00:54,517 Controller polyinterface      ERROR    polyinterface:write: return self.session.api_post_d('ethAccount.asmx/IsSignedIn',{})
2021-10-03 03:00:54,517 Controller polyinterface      ERROR    polyinterface:write: AttributeError
2021-10-03 03:00:54,518 Controller polyinterface      ERROR    polyinterface:write: :
2021-10-03 03:00:54,518 Controller polyinterface      ERROR    polyinterface:write: 'wtServer' object has no attribute 'session'
```

**Comment by jimboca** [comment]
Fixed already, not sure what release.
